bulut_yazilim_doi_generator:
  prefix:   /journal/{journalId}/article/{id}
  resource: "@VipaDoiBundle/Resources/config/routing/generator.yml"

bulut_yazilim_doi_config:
  prefix:   /journal/{journalId}/doi-config
  resource: "@VipaDoiBundle/Resources/config/routing/config.yml"

bulut_yazilim_doi_stats_article:
  prefix:   /admin/stats/doi-article
  resource: "@VipaDoiBundle/Resources/config/routing/stats.yml"

bulut_yazilim_doi_stats_journal:
  path:     /admin/stats/doi-journal
  defaults: { _controller: "VipaDoiBundle:DoiStats:journalDoiDetail"}
  methods: [GET]

bulut_yazilim_doi_crossref_pingback:
  path:     /crossref/pingback
  defaults: { _controller: "VipaDoiBundle:Doi:crossrefPingBack" }
  methods: [GET]
